- name: initialize the cluster
  shell: sudo kubeadm init --pod-network-cidr=192.168.0.0/16  --cri-socket=/var/run/crio/crio.sock  --ignore-preflight-errors Swap >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  file:
    path: /home/k8sadmin/.kube
    state: directory
    mode: 0755

- name: copy admin.conf
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/k8sadmin/.kube/config
    owner: k8sadmin

- name: Install calico Pod network
  become: no
  become_user: k8sadmin
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: "/home/k8sadmin/.kube/config"


- name: Get join token
  become: no
  shell: sudo kubeadm token create  --print-join-command
  register: kubernetes_join_command
 
- name: Copy join command to local file.
  become: no
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- name: Add Helm GPG key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm APT repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install Helm
  apt:
    name: helm
    state: present

- name: Check Helm version
  command: helm version
  register: helm_version_output

- debug:
    var: helm_version_output.stdout_lines

