groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 20
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: " High CPU usage on $labels.instance"
          description: " utilise plus de 20% de son CPU"

      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 60
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on $labels.instance"
          description: " utilise plus de 60% de son CPU"
