- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    
- name: Install Ansible with pip
  ansible.builtin.pip:
    name: ansible
    executable: pip3
    state: present

- name: Copy sudoers file
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 0440
  become: true

