---
- name: Install Docker
  become_user: root
  become: true
  apt:
    name: docker.io
    state: present

- name: Run Prometheus exporter in Docker
  become_user: root
  become: true
  command: "sudo docker run -d -p 9255:9255 prometheuscommunity/stackdriver-exporter --google.project-id elevated-apex-403206 --monitoring.metrics-type-prefixes appengine.googleapis.com/instance --log.level=debug"

